version: '3.3'

services:
  db:
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_DATABASE: 'employee_db'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'passw0rd'
      MYSQL_ROOT_PASSWORD: 'root123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
  front:
    build: ./appx
    restart: always
    environment:
      MYSQL_DATABASE_HOST: db
    depends_on:
      - db
    ports:
      - '8080:5000'
    expose:
      - '5000'