version: '3.3'

services:
  db:
    image: mysql:8.0.34
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
  front:
    build: ./app
    restart: always
    environment:
      MYSQL_DATABASE_HOST: db
    depends_on:
      - db
    ports:
      - '8080:5000'
    expose:
      - '5000'