version: '3.3'

services:
  db:
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_DATABASE: employee_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    expose:
      - '3306'
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    secrets:
      - db_password
      - db_root_password
  front:
    build: ./app
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: employee_db
      DB_USER: db_user
    depends_on:
      - db
    ports:
      - '8080:5000'
    expose:
      - '5000'
    secrets:
      - db_password

secrets:
  db_password:
    file: ./db/db_password.txt
  db_root_password:
    file: ./db/db_root_password.txt